language: cpp
vault:
  api_url: https://vault-central-staging.travis-ci.com
  token:
    secure: ebmvLUbpagjX1xltM8AgMoKdQ9UMibfKvW7qmwZ75tDswducym3aKsjSLF91kzqJSsQf+oKqjEn/Uf9U94Xk0hRvtj0neAJcNpTEaNXEBuHz98zQkmMboRamzDtqXaGGNvpe78sHFvdU/E5Qr5LX7jPdkWxRAtB7e4Ed8472WN+GpEG4vm0zyP8dCTMJy3aJ/NDTK656YW3JZivGUnttmDR7PQWrTBPOTa8aZG1wWygnYK6Nat7rwig8Kpsyj0bkmOER4538tReU4xK3gGCvxELXSIu7+p/tHfsoILxeTpl70tDSNgyqB3akHc3wf6UdG6KxEy5tGYEYLqgFQTqR8C27HZ/7tbM2ZK0AV8vSSGsgxPQILeBJSWGxtcD4JZGThvhn3sJavCg2FGenWodkZt/qQIaVho93LdBFWdKR4aAOl61xgw787eINo75rgSH8ZNDzpPDtx0NOugvuBNHDEXuhs044igi5XgSm3mrMRVeJ8jnEs81Pnh6LP0DnbRKC0yw5VvAoi8lY/TQ92OJyTDR+QmI6vyM1UmvvJnow4xDHr41dwOIAG+czrwPEiOPcNyw388qFeDi3P01ISM+cffLtQXUkj97z+aemAyXDl/PgNb5uwPQ6vDhcSV92myza+JiFVtbV6oSY4HP0kJCSWHe7sfcar3dJVuUeY4brXrQ=
  secrets: 
  - staging-k8s/show/qe2/baztest1
script:
- printenv
