language: python
python:
  - "3.8"
env:
  global:
    secure: kb1L1+0LYExQGoH8I+1Ev7J8n5rMUseAFxboVM0a/Ooo9dd7XjQbYbFUz4xEORi5DKvBO9/T4vnDktpAlpHqfjOabAe4T464wMfSkOjK3DC5j+MqvwmLW8jXECggIBQeGAOSxkN6IpOePHbsuCgGoA3BHQsyvarjZp/nFWnHOzExs77lHYQNTPW1kWYvl8FeG4DkFCtcX4MFI0yPI4+zfDxhKD5W6FX5Z5twl3jCTnPonqgMDtuJhYKgvAkEAtIXQERcCSFR3uhedASgAoPrUcC1wN3XLHvVnwcKVV0S0PoKCM2dhHAtm5b37YRGD79TaF7U0jkMHCx86pqDeMzPSLSHNTbXagjsYr/sk50Qe3Ud+nfQe06t/tWd8WIuOM60h9wFpbNpvhJ60MeFosSSTxMB/ILgYhSHmGIUBzZHeb0qAaMFTxQlwZ50v+XuE0mbT6kaMmGrTY4+VCPp02uXXEygQN+NFakoTIR+GT8ntzZC/F9JR7QE4pXSvFjKcJg/GFF/Jc2yPGkWwNWodMSi20bVIDSje/4Y6ynQlqh2/g2kqFU+VKfQsQhHSI4H6vvAgAPBdUAs3dcjGHVMidRm8gsiOkImzLoR4y7+jFtPnKMDcC3EhOuhlYbH0goqzn934D3yjpoEF9d633COSkbESaPbn8sdsobYPNIiVis7pew=

before_install:
  - echo "$KEY" | base64 -d > decrypted_variable.txt

script:
  - DECRYPTED_VALUE=$(<decrypted_variable.txt)
  - if [ "$DECRYPTED_VALUE" == "test" ]; then echo "Decoded variable is correct"; else echo "Decoded variable is incorrect"; fi
  - echo $DECRYPTED_VALUE
